INSERT INTO Pokemon (name, cp, hp, min_height, max_height , min_weight , max_weight, favourite) VALUES ('Charmander', 100, 200, 1.5, 2.5, 5, 6.5, true);
INSERT INTO Pokemon (name, cp, hp, min_height, max_height , min_weight , max_weight, favourite) VALUES ('Charmeleon', 200, 300, 1, 2, 5, 6.5, false);
INSERT INTO Pokemon (name, cp, hp, min_height, max_height , min_weight , max_weight, favourite) VALUES ('Charizard', 200, 300, 1, 2, 5, 6.5, false);
INSERT INTO Type (name) VALUES ('Fire');
INSERT INTO Type (name) VALUES ('Dragon');
INSERT INTO Pokemon_types VALUES(1,1);
INSERT INTO Pokemon_types VALUES(2,1);
INSERT INTO Pokemon_types VALUES(3,1);
INSERT INTO Pokemon_types VALUES(3,2);
INSERT INTO Pokemon_evolutions VALUES(1,2);
INSERT INTO Pokemon_evolutions VALUES(2,1);
INSERT INTO Pokemon_evolutions VALUES(1,3);
INSERT INTO Pokemon_evolutions VALUES(3,1);
INSERT INTO Pokemon_evolutions VALUES(2,3);
INSERT INTO Pokemon_evolutions VALUES(3,2);
